# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170227_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='project_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
