# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='project_url',
            field=models.URLField(default=0),
        ),
    ]
